# prettier-ignore
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: frontend-secret
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_KAKAO_REST_API_KEY
      remoteRef:
        key: /MINE/MVP1/FE/ENV/COMMON/NEXT_PUBLIC_KAKAO_REST_API_KEY

    - secretKey: NEXT_PUBLIC_PVP_OPEN
      remoteRef:
        key: /MINE/MVP1/FE/ENV/COMMON/NEXT_PUBLIC_PVP_OPEN

    - secretKey: NEXT_PUBLIC_CHALLENGE_OPEN
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_CHALLENGE_OPEN

    - secretKey: NODE_ENV
      remoteRef:
        key: /MINE/MVP1/FE/ENV/COMMON/NODE_ENV

    - secretKey: ALLOW_E2E_LOGIN
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/ALLOW_E2E_LOGIN

    - secretKey: E2E_BASE_URL
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/E2E_BASE_URL

    - secretKey: NEXT_PUBLIC_API_BASE_URL
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_API_BASE_URL

    - secretKey: NEXT_PUBLIC_GOOGLE_ANALYTICS
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_GOOGLE_ANALYTICS

    - secretKey: NEXT_PUBLIC_KAKAO_REDIRECT_URI
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_KAKAO_REDIRECT_URI

    - secretKey: NEXT_PUBLIC_SECURE
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_SECURE

    - secretKey: NEXT_PUBLIC_SERVER_URL
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/NEXT_PUBLIC_SERVER_URL

    - secretKey: PERF_BASE_URL
      remoteRef:
        key: /MINE/MVP1/FE/ENV/PROD/PERF_BASE_URL
