{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-helper
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: backend
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: backend
      containers:
        - name: mine-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          {{- with .Values.backend.secret }}
          {{- if .enabled }}
          envFrom:
            - secretRef:
                name: {{ .name }}
          {{- end }}
          {{- end }}

          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
              memory: {{ .Values.backend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
              memory: {{ .Values.backend.resources.limits.memory | quote }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readinessPath }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.livenessPath }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}

          startupProbe:
            httpGet:
              path: {{ .Values.backend.probes.startupPath }}
              port: {{ .Values.backend.containerPort }}
            periodSeconds: {{ .Values.backend.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.startup.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.backend.probes.startup.failureThreshold }}
{{- end }}