# prettier-ignore
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: AI_SERVER_SECRET
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/AI_SERVER_SECRET

    - secretKey: AWS_REGION
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/AWS_REGION

    - secretKey: BACKEND_URL_DEV
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/BACKEND_URL_DEV

    - secretKey: BACKEND_URL_LOCAL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/BACKEND_URL_LOCAL

    - secretKey: BACKEND_URL_PROD
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/BACKEND_URL_PROD

    - secretKey: BACKEND_URL_REL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/BACKEND_URL_REL

    - secretKey: CORS_ALLOWED_ORIGINS
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/CORS_ALLOWED_ORIGINS

    - secretKey: DB_PASSWORD
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/DB_PASSWORD

    - secretKey: DB_USERNAME
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/DB_USERNAME

    - secretKey: FRONTEND_URL_DEV
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/FRONTEND_URL_DEV

    - secretKey: FRONTEND_URL_LOCAL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/FRONTEND_URL_LOCAL

    - secretKey: FRONTEND_URL_PROD
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/FRONTEND_URL_PROD

    - secretKey: FRONTEND_URL_REL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/FRONTEND_URL_REL

    - secretKey: JWT_SECRET
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/JWT_SECRET

    - secretKey: KAKAO_CLIENT_ID
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/KAKAO_CLIENT_ID

    - secretKey: KAKAO_CLIENT_SECRET
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/KAKAO_CLIENT_SECRET

    - secretKey: RABBITMQ_USER
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/RABBITMQ_USER

    - secretKey: REDIS_PORT
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/REDIS_PORT

    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/S3_ACCESS_KEY

    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/S3_SECRET_KEY

    - secretKey: SENTRY_DSN
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/SENTRY_DSN

    - secretKey: SWAGGER_DEV_SERVER_URL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/COMMON/SWAGGER_DEV_SERVER_URL

    - secretKey: AI_SERVER_URL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/AI_SERVER_URL

    - secretKey: BUCKET_NAME
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/BUCKET_NAME

    - secretKey: DB_URL
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/DB_URL

    - secretKey: KAKAO_REDIRECT_URI
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/KAKAO_REDIRECT_URI

    - secretKey: RABBITMQ_HOST
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/RABBITMQ_HOST

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/RABBITMQ_PASSWORD

    - secretKey: RABBITMQ_PORT
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/RABBITMQ_PORT

    - secretKey: REDIS_HOST
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/REDIS_HOST

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/REDIS_PASSWORD

    - secretKey: SPRING_PROFILES_ACTIVE
      remoteRef:
        key: /MINE/MVP1/BE/ENV/PROD/SPRING_PROFILES_ACTIVE
