# prettier-ignore
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore

  target:
    name: ai-secret
    creationPolicy: Owner

  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/GEMINI_API_KEY

    - secretKey: INTERNAL_SECRET_KEY
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/INTERNAL_SECRET_KEY

    - secretKey: ROOT_PATH
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/ROOT_PATH

    - secretKey: RUNPOD_API_KEY
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/RUNPOD_API_KEY

    - secretKey: RUNPOD_ENDPOINT_ID
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/RUNPOD_ENDPOINT_ID

    - secretKey: RUNPOD_POD_TIMEOUT
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/RUNPOD_POD_TIMEOUT

    - secretKey: RUNPOD_POD_URL
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/RUNPOD_POD_URL

    - secretKey: RABBITMQ_URL
      remoteRef:
        key: /MINE/MVP1/AI/ENV/PROD/RABBITMQ_URL

    - secretKey: REDIS_URL
      remoteRef:
        key: /MINE/MVP1/AI/ENV/PROD/REDIS_URL

    - secretKey: GCP_PROJECT
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/GCP_PROJECT
    
    - secretKey: GCP_LOCATION
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/GCP_LOCATION

    - secretKey: PAIRS_MODEL_ID
      remoteRef:
        key: /MINE/MVP1/AI/ENV/COMMON/PAIRS_MODEL_ID

    - secretKey: GCP_SA_JSON_STR
      remoteRef:
        key: /MINE/MVP1/AI/ENV/PROD/GCP_SA_JSON_STR
